planning_pipelines: ["ompl"]
ompl:
  planning_plugin: "ompl_interface/OMPLPlanner"
  request_adapters: "default_planner_request_adapters/AddTimeOptimalParameterization default_planner_request_adapters/FixWorkspaceBounds default_planner_request_adapters/FixStartStateBounds default_planner_request_adapters/FixStartStateCollision default_planner_request_adapters/FixStartStatePathConstraints"
  start_state_max_bounds_error: 0.1