controller_joint_names: ['arm_left_joint_1_s','arm_left_joint_2_l','arm_left_joint_3_e'
,'arm_left_joint_4_u','arm_left_joint_5_r','arm_left_joint_6_b','arm_left_joint_7_t',
'arm_right_joint_1_s','arm_right_joint_2_l','arm_right_joint_3_e','arm_right_joint_4_u',
'arm_right_joint_5_r','arm_right_joint_6_b','arm_right_joint_7_t','torso_joint_b1','torso_joint_b2']
