topic_list
    - name: sda10f_r1_controller
      ns: sda10f
      group: 1
      joints: ['arm_left_joint_1_s','arm_left_joint_2_l','arm_left_joint_3_e','arm_left_joint_4_u','arm_left_joint_5_r','arm_left_joint_6_b','arm_left_joint_7_t']
    - name: sda10f_r2_controller
      ns: sda10f
      group: 2
      joints: ['arm_right_joint_1_s','arm_right_joint_2_l','arm_right_joint_3_e','arm_right_joint_4_u','arm_right_joint_5_r','arm_right_joint_6_b','arm_right_joint_7_t']
    - name: sda10f_b1_controller
      ns: sda10f
      group: 3
      joints: ['torso_joint_b1']
    - name: sda10f_b2_controller
      ns: sda10f
      group: 4
      joints: ['torso_joint_b2']
