# The cloud
sensor_msgs/PointCloud2 cloud

# starting estimate of bounding box
# all output will be in this frame
# Assumes axis-aligned with header frame, 
# and WON'T take orientation into account.
geometry_msgs/PoseStamped box_pose
geometry_msgs/Vector3     box_dims

# the direction that the container opens (in bounding box header frame)
geometry_msgs/Vector3     opening_dir

---
# refined pose and dimensions of bounding box for container
geometry_msgs/PoseStamped box_pose
geometry_msgs/Vector3     box_dims

# cloud chunks of stuff in container, and container
sensor_msgs/PointCloud2   contents
sensor_msgs/PointCloud2   container
sensor_msgs/PointCloud2[] clusters

---

