# an action for requesting the finger posture part of grasp be physically carried out by a hand
# the name of the arm being used is not in here, as this will be sent to a specific action server
# for each arm

# the grasp to be executed
#manipulation_msgs/Grasp grasp

# the goal of this action
# requests that the hand be set in the pre-grasp posture
int32 PRE_GRASP=1
# requests that the hand execute the actual grasp
int32 GRASP=2
# requests that the hand open to release the object
int32 RELEASE=3
int32 goal

# the max contact force to use (<=0 if no desired max)
float32 max_contact_force

---
# the result of the action
ManipulationResult result

---
# empty for now

