frame_id: world_frame
point_cloud_descriptions:
  - x: -0.8 #target
    y: 0.2
    z: 0.17
    rx: 0.0
    ry: 0.0
    rz: 0.785
    l: 0.17
    w: 0.17
    h: 0.001
    resolution: 0.01
  - x: -0.60 # obstacle
    y: 0.43
    z: 0.10
    rx: 0.0
    ry: 0.0
    rz: 0.0
    l: 0.05
    w: 0.05
    h: 0.20
    resolution: 0.01
  - x: -0.78 # obstacle
    y: -0.40
    z: 0.15
    rx: 0.0
    ry: 0.0
    rz: 0.0
    l: 0.07
    w: 0.05
    h: 0.30
    resolution: 0.01
  - x: -0.60 # obstacle
    y: -0.10
    z: 0.12
    rx: 0.0
    ry: 0.0
    rz: 0.785
    l: 0.07
    w: 0.05
    h: 0.24
    resolution: 0.01
  - x: -0.54 # obstacle
    y: 0.2
    z: 0.06
    rx: 0.0
    ry: 0.0
    rz: 0.0
    l: 0.07
    w: 0.05
    h: 0.12
    resolution: 0.01
