COPY ..\motoros_lib\output\motoros_lib.mpLib motoros_lib.mpLib
COPY ..\motoros_lib\output\mp_default_main.h mp_default_main.h
COPY ..\motoros_lib\output\controller.h controller.h
COPY ..\motoros_lib\output\ParameterExtraction.h ParameterExtraction.h
COPY ..\motoros_lib\output\joint_data.h joint_data.h
COPY ..\motoros_lib\output\simple_message.h simple_message.h
COPY ..\motoros_lib\output\simple_serialize.h simple_serialize.h
COPY ..\motoros_lib\output\shared_types.h shared_types.h
COPY ..\motoros_lib\output\byte_array.h byte_array.h
COPY ..\motoros_lib\output\robot_status.h robot_status.h
