sensor_msgs/PointCloud2 cluster

---

#the pose of the box frame
geometry_msgs/PoseStamped pose

#the dimensions of the box
geometry_msgs/Vector3 box_dims

#whether there was an error
int32 SUCCESS=0
int32 TF_ERROR=1
int32 error_code