"""autogenerated by genpy from soem_beckhoff_drivers/EncoderInMsg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class EncoderInMsg(genpy.Message):
  _md5sum = "b22beb20aeb227634f7e90cad065f8e8"
  _type = "soem_beckhoff_drivers/EncoderInMsg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint8 status
uint16 value
uint16 latch
uint32 frequency
uint16 period
uint16 window

"""
  __slots__ = ['status','value','latch','frequency','period','window']
  _slot_types = ['uint8','uint16','uint16','uint32','uint16','uint16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       status,value,latch,frequency,period,window

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(EncoderInMsg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.status is None:
        self.status = 0
      if self.value is None:
        self.value = 0
      if self.latch is None:
        self.latch = 0
      if self.frequency is None:
        self.frequency = 0
      if self.period is None:
        self.period = 0
      if self.window is None:
        self.window = 0
    else:
      self.status = 0
      self.value = 0
      self.latch = 0
      self.frequency = 0
      self.period = 0
      self.window = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_B2HI2H.pack(_x.status, _x.value, _x.latch, _x.frequency, _x.period, _x.window))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 13
      (_x.status, _x.value, _x.latch, _x.frequency, _x.period, _x.window,) = _struct_B2HI2H.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_B2HI2H.pack(_x.status, _x.value, _x.latch, _x.frequency, _x.period, _x.window))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 13
      (_x.status, _x.value, _x.latch, _x.frequency, _x.period, _x.window,) = _struct_B2HI2H.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_B2HI2H = struct.Struct("<B2HI2H")
