"""autogenerated by genpy from soem_beckhoff_drivers/PSUMsg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class PSUMsg(genpy.Message):
  _md5sum = "1d640ba06d2b65ae841e25741b04ea2c"
  _type = "soem_beckhoff_drivers/PSUMsg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool power_ok
bool overload
"""
  __slots__ = ['power_ok','overload']
  _slot_types = ['bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       power_ok,overload

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PSUMsg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.power_ok is None:
        self.power_ok = False
      if self.overload is None:
        self.overload = False
    else:
      self.power_ok = False
      self.overload = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2B.pack(_x.power_ok, _x.overload))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 2
      (_x.power_ok, _x.overload,) = _struct_2B.unpack(str[start:end])
      self.power_ok = bool(self.power_ok)
      self.overload = bool(self.overload)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2B.pack(_x.power_ok, _x.overload))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 2
      (_x.power_ok, _x.overload,) = _struct_2B.unpack(str[start:end])
      self.power_ok = bool(self.power_ok)
      self.overload = bool(self.overload)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2B = struct.Struct("<2B")
