# Request

# Motion Plan - the trajectory we wish the robot to follow
trajectory_msgs/JointTrajectory motion_plan

# Whether to activate the tool
bool use_tool

---
# Response

# Success and error information
bool success
string message
