# Request

# Mesh - the input to the path planning algorithm
string mesh_filename	# The surfaces on which to generate paths.
string mesh_frame  # Name of the frame to which the mesh vertices are relative

---
# Response

bool success          # Whether the planning was successful
snp_msgs/ToolPaths tool_paths	# The resulting paths
string message        # Information about planning operations
