<?xml version="1.0" ?>
<robot name="mantis_workspace_components" xmlns:xacro="http://ros.org/wiki/xacro">
	<!-- property list -->
	<xacro:property name="workcell_height" value="1"/>
	<xacro:property name="workcell_length" value="2.775"/>
	<xacro:property name="workcell_width" value="2.220"/>		

	<!-- color macros -->
	<xacro:macro name="material_yellow_transparent">
		<material name="yellow_transparent">
			<color rgba="0 1 1 0.4"/>
		</material>
	</xacro:macro>
	<xacro:macro name="material_orange_transparent">
		<material name="orange_transparent">
			<color rgba="1 0.5 0 0.4"/>
		</material>
	</xacro:macro>
	<xacro:macro name="material_gray_transparent">
		<material name="gray_transparent">
			<color rgba="0.6 0.6 0.6 0.4"/>
		</material>
	</xacro:macro>
	<xacro:macro name="material_blue_transparent">
		<material name="blue_transparent">
			<color rgba="0 0.8 1 0.4"/>
		</material>
	</xacro:macro>
	<xacro:material_yellow_transparent />
	<xacro:material_orange_transparent />
	<xacro:material_gray_transparent />
	<xacro:material_blue_transparent />
	<!-- end of color macros -->

	<!-- geometry macros -->	
	<xacro:macro name="workcell_geometry" params="length width height *color_block">
			<geometry>
				<box size="${length} ${width} ${height}"/>
			</geometry>			
			<xacro:insert_block name="color_block"/>
	</xacro:macro>	
	<xacro:macro name="workcell_element" params="name parent length width height offset_x offset_y">
		<link name="${name}">
			<visual>
				<xacro:workcell_geometry length="${length}" width="${width}" height="${height}">
					<material name="gray_transparent"/>
				</xacro:workcell_geometry>
			</visual>
			<collision>
				<xacro:workcell_geometry length="${length}" width="${width}" height="${height}">
					<material name="blue_transparent"/>
				</xacro:workcell_geometry>
			</collision>
		</link>
		<joint name="${parent}_to_${name}" type="fixed">
			<parent link="${parent}"/>
			<child link="${name}"/>
			<origin xyz="${offset_x} ${offset_y} ${0.5 * height}" rpy="0 0 0"/>
		</joint>		
	</xacro:macro>
	<!-- end of geometry macros -->

	<!-- workcell definitions -->
	<link name="world_frame"/>

	<!-- workcell part1 components macro -->
	<xacro:macro name="workcell_zone1_components">
		<link name="table_base1">
			<visual>
				<origin xyz="0 0 ${workcell_height * -0.5}" rpy="0 0 0"/>
				<xacro:workcell_geometry length="${workcell_length * 0.5}" 
					width="${workcell_width}" height="${workcell_height}">
					<material name="orange_transparent"/>
				</xacro:workcell_geometry>
			</visual>
			<collision>
				<origin xyz="0 0 ${workcell_height * -0.5}" rpy="0 0 0"/>
				<xacro:workcell_geometry length="${workcell_length * 0.5}"
					 width="${workcell_width}" height="${workcell_height}">
					<material name="blue_transparent"/>
				</xacro:workcell_geometry>
			</collision>
		</link>
		<joint name="workcell_to_table_base1" type="fixed">
			<parent link="world_frame"/>
			<child link="table_base1"/>
			<origin xyz="${workcell_length * 0.25} 0 0" rpy="0 0 0"/>
		</joint>
		<xacro:workcell_element name="front_wall1" parent="world_frame"
			 length="0.1" width="2.220" height="${workcell_height}" offset_x="1.3375" offset_y="0"/>
		<!--xacro:workcell_element name="back_wall1" parent="world_frame"
			 length="0.04" width="2.00" height="${workcell_height}" offset_x="0.02" offset_y="0"/-->
		<xacro:workcell_element name="left_wall1" parent="world_frame"
			 length="1.221" width="0.1" height="${workcell_height}" offset_x="0.687" offset_y="1.060"/>
		<xacro:workcell_element name="right_wall1" parent="world_frame"
			 length="1.221" width="0.1" height="${workcell_height}" offset_x="0.687" offset_y="-1.060"/>
	</xacro:macro>
	<!-- end of workcell part1 components macro -->	

	<!-- workcell part2 components macro -->
	<xacro:macro name="workcell_zone2_components">
		<link name="table_base2">
			<visual>
				<origin xyz="0 0 ${workcell_height * -0.5}" rpy="0 0 0"/>
				<xacro:workcell_geometry length="${workcell_length * 0.5}" 
					width="${workcell_width}" height="${workcell_height}">
					<material name="orange_transparent"/>
				</xacro:workcell_geometry>
			</visual>
			<collision>
				<origin xyz="0 0 ${workcell_height * -0.5}" rpy="0 0 0"/>
				<xacro:workcell_geometry length="${workcell_length * 0.5}"
					 width="${workcell_width}" height="${workcell_height}">
					<material name="blue_transparent"/>
				</xacro:workcell_geometry>
			</collision>
		</link>
		<joint name="workcell_to_table_base2" type="fixed">
			<parent link="world_frame"/>
			<child link="table_base2"/>
			<origin xyz="${workcell_length * -0.25} 0 0" rpy="0 0 0"/>
		</joint>
		<xacro:workcell_element name="front_wall2" parent="world_frame"
			 length="0.1" width="2.220" height="${workcell_height}" offset_x="-1.3375" offset_y="0"/>		 
		<!--xacro:workcell_element name="back_wall2" parent="world_frame"
			 length="0.04" width="2.00" height="${workcell_height}" offset_x="-0.02" offset_y="0"/-->
		<xacro:workcell_element name="left_wall2" parent="world_frame" 
			length="1.384" width="0.1" height="${workcell_height}" offset_x="-0.601" offset_y="1.060"/>
		<xacro:workcell_element name="right_wall2" parent="world_frame" 
			length="1.384" width="0.1" height="${workcell_height}" offset_x="-0.601" offset_y="-1.060"/>
		<xacro:workcell_element name="cover_part1" parent="world_frame"
			 length="0.229" width="0.508" height="0.14" offset_x="-0.042" offset_y="-0.081"/>
		<xacro:workcell_element name="cover_part2" parent="world_frame"
			 length="0.121" width="0.260" height="0.14" offset_x="-0.012" offset_y="-0.465"/>
	</xacro:macro>
	<!-- end of workcell part1 components macro -->
</robot>
