<?xml version="1.0" ?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
	<!-- parameter list -->
	<xacro:property name="gripper_length" value="0.044"/>
	<xacro:property name="gripper_width" value="0.088"/>
	<xacro:property name="gripper_height" value="0.0946"/>
	<xacro:property name="gripper_body_height" value="0.16"/>

	<xacro:macro name="vacuum_gripper_definition" params="prefix gripper_adjustment">
		<link name="${prefix}gripper_frame"/>
		<link name="${prefix}gripper_body">
			<visual>
				<!--origin xyz="0 0.036 -0.0473" rpy="0 0 0"/-->
				<!--geometry>
					<box size="${gripper_length} ${gripper_width} ${gripper_height}"/>
				</geometry-->
				<origin xyz="0 0 -0.048" rpy="0 0 0"/>
				<geometry>
					<mesh filename="package://robot_workcell_support/meshes/vacuum_gripper_single_suction_cup.STL" />
				</geometry>
				<material name="silver">
					<color rgba="0.8 0.8 0.8 1"/>
				</material>
			</visual>
			<collision>
				<!--<origin xyz="0 0 0.03"/>-->
				<geometry>
					<box size="${gripper_length} ${gripper_width} ${gripper_body_height}"/>
				</geometry>
				<material name="another_blue2">
					<color rgba="0.38 0.54 0.83 1"/>
				</material>
			</collision>
		</link>
		<link name="${prefix}tcp_frame">
			<visual>								
				<geometry>
					<sphere radius="0.005"/>
				</geometry>
				<material name="white">
					<color rgba="1 1 1 0.5"/>
				</material>
			</visual>
		</link>	
		<joint name="${prefix}gripper_to_palm" type="fixed">
			<parent link="${prefix}gripper_frame"/>
			<child link="${prefix}gripper_body"/>
			<origin xyz="0 0 ${gripper_height * 0.5}" rpy="0 0 0"/>
		</joint>
		<joint name="${prefix}gripper_to_tcp" type="fixed">
			<parent link="${prefix}gripper_frame"/>
			<child link="${prefix}tcp_frame"/>
			<origin xyz=" 0 ${gripper_length * 0.5} ${0.12 + gripper_adjustment}" rpy="0 0 0"/>
		</joint>	
	</xacro:macro>
</robot>
