# configuration for controllers managed by moveit
controller_names:
  - manipulator_joint_trajectory_controller
  
manipulator_joint_trajectory_controller:
  action_ns: follow_joint_trajectory
  default: True
  type: FollowJointTrajectory
  joints:
    - elbow_joint
    - shoulder_lift_joint
    - shoulder_pan_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint

