sensors: 
 - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
   sensor_frame: world_frame
   point_cloud_topic: /filtered_cloud
   max_range: 5.0
   frame_subsample: 1
   point_subsample: 1
   padding_offset: 0.02
   padding_scale: 1.0
#   filtered_cloud_topic: octomap_cloud # enable when need to republish process cloud from move_group

