<?xml version="1.0" ?>
<robot name="ur5_workcell" xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:include filename="$(find robot_workcell_support)/urdf/vacuum_gripper_macro.xacro"/>    
    <xacro:include filename="$(find ur_description)/urdf/ur_macro.xacro"/>
    <xacro:include filename="$(find robot_workcell_support)/urdf/workspace_components.xacro"/>
    <xacro:include filename="$(find robot_workcell_support)/urdf/kinect_sensor_macro.xacro"/>

    <!-- property list -->
    <xacro:property name="workcell_height" value="1"/>
    <xacro:property name="robot_stand_height" value="0.20"/>
    <xacro:property name="vacuum_gripper_width" value="0.088"/>
    <xacro:property name="attached_object_length" value="0.17"/>
    <xacro:property name="attached_object_width" value="0.17"/>
    <xacro:property name="attached_object_height" value="0.17"/>
    <xacro:property name="arm_prefix" value=""/>

    <!-- instantiating robot arm and gripper -->    
    <!-- ur parameters -->
    <xacro:arg name="prefix" default="${arm_prefix}"/><!-- Remove once PR https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/pull/149 is merged-->
    <xacro:arg name="ur_type" default="ur5"/>
    <xacro:arg name="joint_limit_params" default="$(find ur_description)/config/$(arg ur_type)/joint_limits.yaml"/>
    <xacro:arg name="kinematics_params" default="$(find ur_description)/config/$(arg ur_type)/default_kinematics.yaml"/>
    <xacro:arg name="physical_params" default="$(find ur_description)/config/$(arg ur_type)/physical_parameters.yaml"/>
    <xacro:arg name="visual_params" default="$(find ur_description)/config/$(arg ur_type)/visual_parameters.yaml"/>
		
	<xacro:arg name="transmission_hw_interface" default=""/>
	<xacro:arg name="safety_limits" default="false"/>
	<xacro:arg name="safety_pos_margin" default="0.15"/>
	<xacro:arg name="safety_k_position" default="20"/>
	
	<!-- ros2_control related parameters -->
	<xacro:arg name="use_fake_hardware" default="true" />
	<xacro:arg name="fake_sensor_commands" default="false" />
	<xacro:arg name="robot_ip" default="10.0.1.186"/>
	
	<!-- ros2 fake_components/generic_system  initial joints -->
	<xacro:arg name="initial_positions_file" default=""/>
	<xacro:property name="initial_positions_file_" value="$(arg initial_positions_file)"/>
	<xacro:if value="${initial_positions_file_ == ''}">
	  <xacro:property name="initial_positions" value="${dict(shoulder_pan_joint=0,shoulder_lift_joint=-1.57,elbow_joint=0,wrist_1_joint=-1.57,wrist_2_joint=0.0,wrist_3_joint=0.0)}" />
	</xacro:if>
	<xacro:if value="${initial_positions_file_ != ''}">
	  <xacro:property name="initial_positions" value="${load_yaml(initial_positions_file_)}"/>
	</xacro:if>

   <!-- ur arm instantiation -->
   <xacro:ur_robot
     name="ur5"
     tf_prefix="${arm_prefix}"
     parent="ur5_stand"
     joint_limits_parameters_file="$(arg joint_limit_params)"
     kinematics_parameters_file="$(arg kinematics_params)"
     physical_parameters_file="$(arg physical_params)"
     visual_parameters_file="$(arg visual_params)"
     transmission_hw_interface="$(arg transmission_hw_interface)"
     safety_limits="$(arg safety_limits)"
     safety_pos_margin="$(arg safety_pos_margin)"
     safety_k_position="$(arg safety_k_position)"
     use_fake_hardware="$(arg use_fake_hardware)"
     fake_sensor_commands="$(arg fake_sensor_commands)"
     initial_positions="${initial_positions}" >
       <origin xyz="0 0 ${robot_stand_height * 0.5}" rpy="0 0 2.355"/>
    </xacro:ur_robot>
    
    <!-- instantiating robot arm and gripper -->
    <xacro:vacuum_gripper_definition prefix="${arm_prefix}" gripper_adjustment="0.01"/>

    <!-- instantiating workcell definitions -->
    <xacro:workcell_zone2_components/>
    <!-- end of workcell definitions -->

    <!-- arm-workcell link definitions -->
    <link name="ur5_stand">
            <visual>
                    <geometry>
                            <cylinder radius="0.0735" length="${robot_stand_height}"/>
                    </geometry>
                    <material name="orange_transparent"/>
            </visual>
            <collision>
                    <geometry>
                            <cylinder radius="0.0735" length="${robot_stand_height}"/>
                    </geometry>
                    <material name="blue_transparent"/>
            </collision>
    </link>


    <link name="base_padding">
            <collision>
                    <geometry>
                            <cylinder radius="0.14" length="${robot_stand_height * 2}"/>
                    </geometry>
                    <material name="blue_transparent"/>
            </collision>
    </link>

    <!-- instantiating sensor definitions -->

    <xacro:sensor_definitions prefix="${arm_prefix}" parent_link="world_frame"
            x_val="-1.0414" y_val="0" z_val="1.18745" pitch="1.57" yaw="0" roll="0" />
    <!-- end of sensor definitions -->

    <joint name="world_to_stand" type="fixed">
            <parent link="world_frame"/>
            <child link="ur5_stand"/>
            <origin xyz="-0.238 0 ${robot_stand_height * 0.5}"/>
    </joint>

    <joint name="world_to_base_padding" type="fixed">
            <parent link="world_frame"/>
            <child link="base_padding"/>
            <origin xyz="-0.238 0 ${robot_stand_height}"/>
    </joint>


    <!-- end of arm-workcell link definitions -->

    <!-- end of arm workcell joint definitions-->

    <!-- arm-gripper coupling joint definitions -->
    <joint name="${arm_prefix}wrist_to_gripper" type="fixed">
            <parent link="${arm_prefix}tool0"/>
            <child link="${arm_prefix}gripper_frame"/>
            <origin xyz="0 0 0" rpy="0 0 0"/> <!-- 0 1.57 0 -->
    </joint>
    <!-- end of arm-gripper coupling joint definitions -->  
</robot>