joint_limits:
  joint_t:
    has_velocity_limits: true
    max_velocity: 6.97
    has_acceleration_limits: true
    max_acceleration: 1
  joint_r:
    has_velocity_limits: true
    max_velocity: 3.48
    has_acceleration_limits: true
    max_acceleration: 1
  joint_u:
    has_velocity_limits: true
    max_velocity: 2.96
    has_acceleration_limits: true
    max_acceleration: 1
  joint_s:
    has_velocity_limits: true
    max_velocity: 2.26
    has_acceleration_limits: true
    max_acceleration: 1
  joint_l:
    has_velocity_limits: true
    max_velocity: 2.26
    has_acceleration_limits: true
    max_acceleration: 1
  joint_e:
    has_velocity_limits: true
    max_velocity: 2.96
    has_acceleration_limits: true
    max_acceleration: 1
  joint_b:
    has_velocity_limits: true
    max_velocity: 3.48
    has_acceleration_limits: true
    max_acceleration: 1
