# -*- coding: utf-8 -*-
#
# SphinxTest documentation build configuration file, created by
# sphinx-quickstart on Tue Oct  3 11:09:13 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
from sphinx import version_info as sphinx_version_info
import os
import git
curr_path = os.path.abspath('.')
# The try catch is need because of the subversion tool when it creates the master.
try:
  repo = git.Repo(curr_path)
  current_branch = repo.active_branch.name
except git.exc.InvalidGitRepositoryError:
  current_branch = ''


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['sphinx.ext.githubpages', 'recommonmark']

if sphinx_version_info >= (1, 4):
  extensions += ['recommonmark']
else:
  from recommonmark.parser import CommonMarkParser

  source_parsers = {
      '.md': CommonMarkParser,
  }

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

source_suffix = ['.rst', '.md']

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'Industrial Training'
copyright = u'2020, ROS-Industrial'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = current_branch
# The full version, including alpha/beta/rc tags.
release = current_branch

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store', 'README.md', 'exercise']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

download_support = True

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'
html_theme_path = ['_themes',]

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {
    #'canonical_url': '',
    'analytics_id': '',
    'logo_only': False,
    'display_version': True,
    'prev_next_buttons_location': 'bottom',
    'style_external_links': False,
    #'vcs_pageview_mode': '',
    # Toc options
    'collapse_navigation': True,
    'sticky_navigation': False,
    'navigation_depth': 4,
    'includehidden': True,
    'titles_only': False,
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

html_context = {
    #"wiki_title": "ROS-Industrial Training Material",
    "display_github": True,
    "github_user": "ros-industrial",
    "github_repo": "industrial_training",
    "github_version": current_branch,
    "conf_py_path": "gh_pages/",
    "source_suffix": source_suffix,
    "css_files": ['_static/override.css'],
}

# Output file base name for HTML help builder.
htmlhelp_basename = 'IndustrialTrainingDocumentation'

