controller_list:
  - name: fake_manipulator_controller
    joints:
      - joint_s
      - joint_l
      - joint_u
      - joint_r
      - joint_b
      - joint_t
  - name: fake_vacuum_gripper_controller
    joints:
      []