# Requests that a list of possible place locations be generated for a given object

# the arm being used
string arm_name

# the object to be placed
manipulation_msgs/GraspableObject target

# a default orientation for the object when placed
# this is somewhat specific to the interactive manipulation tool gripper_click
# and should be removed in the future
geometry_msgs/Quaternion default_orientation

# The position of the end-effector for the grasp relative to the object
geometry_msgs/Pose grasp_pose

# the name that the target object has in the collision environment
# can be left empty if no name is available
string collision_object_name

# the name that the support surface (e.g. table) has in the collision map
# can be left empty if no name is available
string collision_support_surface_name

---

# the list of planned grasps
geometry_msgs/PoseStamped[] place_locations

# whether an error occurred
GraspPlanningErrorCode error_code
